### ISSUE TITLE
Duplicate prefix breaks run

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/automate-pheno-comparisons#1]
Run 9 fails while doing similarity, due to:
```
curies.api.DuplicateURIPrefixes: Duplicate URI prefixes:
11:07:38  
11:07:38  https://icd.who.int/browse10/2019/en#/:
11:07:38  	prefix='ICD10WHO' uri_prefix='https://icd.who.int/browse10/2019/en#/' prefix_synonyms=[] uri_prefix_synonyms=[]
11:07:38  	prefix='icd10who' uri_prefix='https://icd.who.int/browse10/2019/en#/' prefix_synonyms=[] uri_prefix_synonyms=[]
11:07:38  
```

The previous (aborted) build did not encounter this error in >8 hours of similarity calc, so I'm guessing something changed upstream.
`curies` is still the same version (0.5.5) in runs 8 and 9.
`prefixmaps` is 0.1.5 in both runs 8 and 9.

**Comment by justaddcoffee** [comment]
I'm trying to understand this error - so this is the [curies](https://pypi.org/project/curies/) package complaining because there are duplicate mappings for `ICD10WHO`, which is considered the same as `icd10who` because case is not considered?

Where are the prefix maps coming from exactly?

**Comment by caufieldjh** [comment]
I think this is actually due to a new build of PHENIO - this process gets phenio.db.gz from https://s3.amazonaws.com/bbop-sqlite/ , and the build there just got updated yesterday after the time the "working" Jenkins run started

**Comment by caufieldjh** [comment]
This is present for all similarity commands in OAK using semsimian: https://github.com/INCATools/ontology-access-kit/issues/606

**Comment by caufieldjh** [comment]
> This is super weird.. Is there an exception/error message with more info?
yep, see that OAK issue

**Comment by caufieldjh** [comment]
Fixed by https://github.com/INCATools/semantic-sql/commit/ea764b1d884930723f16369f830be082da85bfb9
