### ISSUE TITLE
Determine whether PHENIO edges are necessary in calculating HP vs HP semsim

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/automate-pheno-comparisons#31]
As per discussion w/ @justaddcoffee and @julesjacobsen, the most recent build prepares semsim values for both of the following:
* HP vs HP, through PHENIO
* HP vs HP, through HP alone
The thought being that PHENIO edges won't contribute to a comparison of all vs all within a single ontology.
In both of these builds, the IC cutoff was 1.5 and ICs are based on HPOA frequency.
Some of the increased size of these builds is because they now contain ID labels.

So how do they differ?
Below, I will refer to HP vs HP, through PHENIO as "PHENIO" and HP vs HP, through HP alone as "Alone".

Compressed size:
* PHENIO: ~586 Mb
* Alone: ~465 Mb

Uncompressed size of semsim table alone:
* PHENIO: ~4.2 Gb, 22332765 lines
* Alone: ~4.3 Gb, 23580617 lines

**Comment by justaddcoffee** [comment]
>Uncompressed size of semsim table alone:
>
> PHENIO: ~4.2 Gb, 22332765 lines
> Alone: ~4.3 Gb, 23580617 lines

This might seem weird, but is plausible: using HP alone possibly produces more pairs of HP terms that meet the IC cutoff, so the file is bigger

**Comment by caufieldjh** [comment]
See also https://github.com/Knowledge-Graph-Hub/automate-pheno-comparisons/issues/30

**Comment by caufieldjh** [comment]
URLs for the above:
* https://kghub.io/monarch/semsim/HP_vs_HP_semsimian_hp.tsv.tar.gz
* https://kghub.io/monarch/semsim/HP_vs_HP_semsimian_phenio.tsv.tar.gz
* https://kghub.io/monarch/semsim/HP_vs_MP_semsimian_phenio.tsv.tar.gz
* https://kghub.io/monarch/semsim/HP_vs_ZP_semsimian_phenio.tsv.tar.gz
